### ISSUE TITLE
Problem installing StatsBombR package

### ISSUE THREAD

**Issue by marcosnioac** [statsbomb/StatsBombR#13]
I am having a problem too. Done all the install.packages stuff, but still getting this:

Downloading GitHub repo statsbomb/StatsBombR@HEAD
Error: Failed to install 'StatsBombR' from GitHub:
  Git does not seem to be installed on your system.

What it could be?  :(

**Comment by timschott** [comment]
Do you have git installed in on your system? If you've only looked at things on github.com, but not worked with repos directly on your machine, you may not. See the git [docs:](https://git-scm.com/download/mac) you may need to do something like install [homebrew](https://brew.sh/) then run `brew install git`

**Comment by asinofsky** [comment]
Hi @timschott ! I'm having the same problem but I'm pretty sure I do have git installed on my system... i use it with bitbucket to pull and push from repos etc. so it must be there, right? Is it a path thing, in that case?

**Comment by EuanDewar** [comment]
@asinofsky Hi, can you please add the full output of your errors?

Thanks

**Comment by asinofsky** [comment]
Hey! Sorry I think I eventually got through it but I was a bad
internet/github participant and forgot to report back in. I believe I was
just dealing with path variables, R versions, package versions,
dependencies and such for a while and got through it. My bad on not
reporting back with more specifics at the time.
