### ISSUE TITLE
Issues installing SDMTools and StatsBombR

### ISSUE THREAD

**Issue by JaseZiv** [statsbomb/StatsBombR#16]
Hi there,

When trying to install both 'SDMTools' and 'StatsBombR', I'm getting the following error message:

```
devtools::install_github("statsbomb/StatsBombR")

Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo statsbomb/StatsBombR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  cannot open URL 'https://api.github.com/repos/statsbomb/StatsBombR/tarball/HEAD'
```

```
devtools::install_github("statsbomb/SDMTools")

Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo statsbomb/SDMTools@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  cannot open URL 'https://api.github.com/repos/statsbomb/SDMTools/tarball/HEAD'
```

Results of `sessionInfo()`:
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1    usethis_2.0.1     devtools_2.4.2    pkgload_1.2.1    
 [5] R6_2.5.0          rlang_0.4.11      fastmap_1.1.0     tools_4.1.0      
 [9] pkgbuild_1.2.0    xfun_0.29         sessioninfo_1.1.1 tinytex_0.33     
[13] cli_3.0.1         withr_2.4.2       ellipsis_0.3.2    remotes_2.4.0    
[17] rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.5.2   
[21] purrr_0.3.4       callr_3.7.0       fs_1.5.0          ps_1.6.0         
[25] curl_4.3.2        testthat_3.0.4    memoise_2.0.0     glue_1.4.2       
[29] cachem_1.0.5      compiler_4.1.0    desc_1.3.0        prettyunits_1.1.1
```

**Comment by EuanDewar** [comment]
Hi,

Can you try updating your R version? This is a new issue to me and certainly has not been present thus far on more recent versions from what I've seen.

Thanks,

**Comment by JaseZiv** [comment]
> Hi,
> 
> Can you try updating your R version? This is a new issue to me and certainly has not been present thus far on more recent versions from what I've seen.
> 
> Thanks,

Updated to `R 4.2.0` and the exact errors persist?

**Comment by EuanDewar** [comment]
Have you had a look at things like this?

https://github.com/r-lib/devtools/issues/1566

**Comment by JaseZiv** [comment]
> Have you had a look at things like this?
> 
> [r-lib/devtools#1566](https://github.com/r-lib/devtools/issues/1566)

Yeah should've added in my original post that I had tried removing the environment variable `GITHUB_PAT` and had the same result...

**Comment by EuanDewar** [comment]
Apologies but I'm fairly sure this isn't related to our package, the best I can offer is looking at other people's solutions for similar errors such as:

https://github.com/r-lib/remotes/issues/130#issuecomment-423830669

**Comment by stxlen** [comment]
Euan, I'm receiving a different error but I think it's because of the same above... `SDMTools` does not  look to be compatible with `R 4.2.0` . https://community.rstudio.com/t/trouble-with-installing-sdmtools/135369

**Comment by EuanDewar** [comment]
Have you tried the changed installation method on the SBR github page? 
devtools::install_github("statsbomb/SDMTools")

**Comment by stxlen** [comment]
Ahhh that looks to have done the trick. Thanks!

**Comment by Rohit-Satyam** [comment]
`devtools::install_github("cran/SDMTools")` worked for me
