### ISSUE TITLE
Error with the StatsBombFree360Events function

### ISSUE THREAD

**Issue by alickmighall** [statsbomb/StatsBombR#18]
This seems similar to the error reported [here](https://github.com/statsbomb/StatsBombR/issues/17), which is detailed in this [comment](https://github.com/statsbomb/StatsBombR/issues/17#issuecomment-1190433233).

**Comment by EuanDewar** [comment]
Hi,

I've just added a function called free_allevents_360. Update and try that one.

Best,

**Comment by alickmighall** [comment]
Thanks for looking at that so quickly @EuanDewar  - that works!

You may want to get this section in this [blog post](https://statsbomb.com/news/statsbomb-announce-the-release-of-free-statsbomb-360-data-euro-2020-available-now/) updated to take into account this issue and [issue 17](https://github.com/statsbomb/StatsBombR/issues/18)

_First, let’s pull the 360 freeze-frames and store them in a dataframe ‘data360’.

library (StatsBombR)

Comp <- FreeCompetitions()
Matches <- FreeMatches(Comp)
Matches = Matches %>% filter(competition.competition_name==”UEFA Euro”)
data360 <- StatsBombFree360Events(MatchesDF = Matches, Parallel = T)

Next, we’re going to pull the standard Euro 2020 event data into a separate dataframe.

events <- StatsBombFreeEvents(MatchesDF = Matches, Parallel = T)
events <- allclean(events)
events <- get.opposingteam(events)_

**Comment by EuanDewar** [comment]
Ah good shout. I'll get the marketing folks to look at that. Thanks
